canonical_emotions:
  neutral:
    tag: "(indifferent)"
    aliases:
      - neu
      - neutral
      - normal
      - calm
      - plain
      - default
  happy:
    tag: "(happy)"
    aliases:
      - hap
      - happy
      - happiness
      - joy
      - joyful
  sad:
    tag: "(sad)"
    aliases:
      - sad
      - sadness
      - sorrow
  angry:
    tag: "(angry)"
    aliases:
      - ang
      - angry
      - anger
      - mad
  anxious:
    tag: "(anxious)"
    aliases:
      - fea
      - anxious
      - anxiety
      - fear
      - fearful
      - afraid
  hurt:
    tag: "(painful)"
    aliases:
      - dis
      - disgust
      - disgusted
      - hurt
      - wounded
      - pain
      - painful
  embarrassed:
    tag: "(embarrassed)"
    aliases:
      - sur
      - surprise
      - surprised
      - embarrassed
      - embarrassment
      - awkward

default_emotion: neutral
